### ISSUE TITLE
[bug] Chlorella calculator problem

### ISSUE THREAD

**Issue by TheGlider0** [45026831/hh-booster-detector#1]
See attached image. Calculating expected ego correctly but considering it boosted anyway.

Hentai Heroes++ BDSM version | 0.32.12
Hentai Heroes Style Tweaks | 0.2.15

![Untitled](https://user-images.githubusercontent.com/90114177/132108176-1219edff-60ce-4cb3-b22c-608efb01c65c.png)

**Comment by 45026831** [comment]
Can you please include the booster detector version and the console output for the Chlorella check, please?

**Comment by TheGlider0** [comment]
Hentai Heroes++ League Booster Detector Add-on | 0.0.17

Console output of the booster detector:
#######################
CORDYCEPS CHECK: Expected: 67575.54000000001, Actual: 67136, Extra: -1%
userscript.html?name=Hentai%20Heroes%2B%2B%20League%20Booster%20Detector%20Add-on.user.js&id=6c55d2b2-536b-4490-ab7c-42ea349ae14c:232 CHLORELLA CHECK: Expected: 420529.24, Actual: 424000, Extra: 1%
userscript.html?name=Hentai%20Heroes%2B%2B%20League%20Booster%20Detector%20Add-on.user.js&id=6c55d2b2-536b-4490-ab7c-42ea349ae14c:273 GINSENG CHECK: Expected: 77140.8, Actual: 83217.28, Extra: -2%, Monostat count: 0, Has club: true
userscript.html?name=Hentai%20Heroes%2B%2B%20League%20Booster%20Detector%20Add-on.user.js&id=6c55d2b2-536b-4490-ab7c-42ea349ae14c:288 JUJUBES CHECK: Expected: 72902, Actual: 73045, Extra: 0%, Monostat count: 0, Has club: true
#######################

**Comment by 45026831** [comment]
Published v0.1.0 ( a728cbd ) which will help with visualisations of edge cases like this.
